runtime: python39  # Specify the Python version
entrypoint: gunicorn -b :$PORT flask_vedic:app  # Ensure correct Flask app is called

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
